import * as React from 'react';
import type { ProjectMeta } from '@/components/content/ProjectLayout';
import { ProjectGallery } from '@/components/lightbox/ProjectGallery';

import cover from './sonora-cover.jpg';
import sessionsImg from './sessions.png';
import recapsImg from './recaps.png';
import treemapsImg from './treemaps.png';
export const meta: ProjectMeta = {
  slug: 'sonora',
  title: 'Sonora',
  year: 2025,
  context: 'CMD',
  description: 'A Spotify visualizer that turns your currently playing track into a live, data-driven vinyl record.',
  roles: ['💻 DEV', '🎨 UI'],
  tags: ['Svelte(kit)', 'D3', 'HTML', 'CSS', 'JavaScript'],
  cover,
  links: [
    {
      label: 'Source Code',
      href: 'https://github.com/kokjp1/TechTrack',
    },
    {
      label: 'Live App',
      href: 'https://www.sonora.stream/',
    },
  ],
};

export default function Body() {
  const galleryImages = [
    { src: recapsImg, alt: 'Sonora Recaps', caption: 'Sonora Recap View' },
    { src: treemapsImg, alt: 'Sonora Treemap', caption: 'Sonora Treemap View' },
  ];

  return (
    <>
      <p>
        Sonora is a web app that visualizes your Spotify listening session as a spinning vinyl record. Every track gets its own "custom vinyl" shaped and styled by the actual data behind the song.
      </p>

      <h2 className="mt-8 mb-4 text-lg font-semibold">How the vinyl maps to data:</h2>
      <ul className="list-disc pl-5 space-y-2 mb-8">
        <li><strong>Size of the record</strong> → track popularity score</li>
        <li><strong>Rotation speed</strong> → track duration or popularity</li>
        <li><strong>Number of grooves</strong> → release year (older = more grooves)</li>
        <li><strong>Color &amp; glow</strong> → extracted from the album cover via <code>node-vibrant</code></li>
      </ul>

      <p>
        The vinyl only spins when a track is actually playing, it syncs live with your Spotify session via the Spotify API (OAuth). Alongside the vinyl, a treemap visualization shows the distribution of genres and artists across your session.
      </p>

      <p className="mt-4 font-medium max-w-none prose dark:prose-invert">Built with: SvelteKit, Spotify Web API and <a href="https://github.com/Vibrant-Colors/node-vibrant"><u>node-vibrant</u></a></p>

      <h2 className="mt-8 mb-4 text-lg font-semibold">If I had more time for the project;</h2>
      <ul className="list-disc pl-5 space-y-2 mb-8 text-sm">
        <li>I'd have liked to have a textual summary of your listening session. Autogenerated via templating it could've been something like: "Your session consisted mostly of [genre], with a sudden switch to [genre] at [time]"</li>
      </ul>

      

      <h2 className="mt-8 text-lg font-semibold">gallery</h2>
      <div className="mt-6">
        <ProjectGallery
          splash={{ src: sessionsImg, alt: 'Sonora Session View', caption: 'Live Session View, Synced with Spotify' }}
          images={galleryImages}
          gridClasses="grid-cols-2"
        />
      </div>
    </>
  );
}
